/* ════════════════════════════════════════════════════════════════════
   sort.js — Part 1: Sorting Algorithm Comparison
   Data structure used: Array (random-access, index-based)
   All 8 algorithms track comparisons and swaps for analysis.
   ════════════════════════════════════════════════════════════════════ */

const SortModule = (() => {

  /* ── ALGORITHM IMPLEMENTATIONS ──────────────────────────────────── */
  /* Each returns { sorted[], comps, swaps, steps[] }
     steps[] are used by the live bar visualizer.
     Data structure: JavaScript Array (dynamic array, O(1) access)     */

  /**
   * BUBBLE SORT — O(n²) average/worst, O(n) best
   * Repeatedly swaps adjacent out-of-order pairs.
   * Early-exit optimization: stops if a pass made no swaps.
   * Data structure: in-place array manipulation
   */
  function bubbleSort(arr) {
    const a = arr.slice(); const n = a.length;
    let comps = 0, swaps = 0;
    const steps = [];
    for (let i = 0; i < n; i++) {
      let swapped = false;
      for (let j = 0; j < n - i - 1; j++) {
        comps++;
        if (a[j] > a[j + 1]) {
          [a[j], a[j + 1]] = [a[j + 1], a[j]]; swaps++; swapped = true;
          steps.push({ arr: a.slice(), hi: j, lo: j + 1, comps, swaps });
        }
      }
      if (!swapped) break; // already sorted
    }
    return { sorted: a, comps, swaps, steps };
  }

  /**
   * SELECTION SORT — O(n²) all cases
   * Each pass finds the minimum in the unsorted portion, places it at front.
   * Data structure: in-place array, single index pointer for minimum
   */
  function selectionSort(arr) {
    const a = arr.slice(); const n = a.length;
    let comps = 0, swaps = 0;
    const steps = [];
    for (let i = 0; i < n; i++) {
      let mi = i;
      for (let j = i + 1; j < n; j++) { comps++; if (a[j] < a[mi]) mi = j; }
      if (mi !== i) { [a[i], a[mi]] = [a[mi], a[i]]; swaps++; }
      steps.push({ arr: a.slice(), hi: i, lo: mi, comps, swaps });
    }
    return { sorted: a, comps, swaps, steps };
  }

  /**
   * INSERTION SORT — O(n²) average/worst, O(n) best
   * Builds a sorted prefix; each element is inserted at its correct position.
   * Data structure: in-place array, key variable (like inserting into a sorted hand of cards)
   */
  function insertionSort(arr) {
    const a = arr.slice();
    let comps = 0, swaps = 0;
    const steps = [];
    for (let i = 1; i < a.length; i++) {
      const key = a[i]; let j = i - 1;
      while (j >= 0) {
        comps++;
        if (a[j] > key) { a[j + 1] = a[j]; swaps++; j--; } else break;
      }
      a[j + 1] = key;
      steps.push({ arr: a.slice(), hi: i, lo: j + 1, comps, swaps });
    }
    return { sorted: a, comps, swaps, steps };
  }

  /**
   * MERGE SORT — O(n log n) all cases, O(n) space
   * Divide-and-conquer: split array in halves, sort recursively, merge.
   * Data structure: auxiliary arrays for merging (not in-place)
   * Visual steps generated by simulating the merge passes iteratively.
   */
  function mergeSort(arr) {
    let comps = 0;
    const steps = [];

    function merge(L, R) {
      const out = []; let i = 0, j = 0;
      while (i < L.length && j < R.length) {
        comps++;
        if (L[i] <= R[j]) out.push(L[i++]); else out.push(R[j++]);
      }
      return out.concat(L.slice(i)).concat(R.slice(j));
    }
    function msort(a) {
      if (a.length <= 1) return a;
      const m = Math.floor(a.length / 2);
      return merge(msort(a.slice(0, m)), msort(a.slice(m)));
    }
    const sorted = msort(arr.slice());

    // generate visual steps via iterative bottom-up merge passes
    let tmp = arr.slice();
    for (let sz = 1; sz < arr.length; sz *= 2) {
      const nxt = tmp.slice();
      for (let lo = 0; lo < tmp.length; lo += sz * 2) {
        const mid = Math.min(lo + sz, tmp.length);
        const hi  = Math.min(lo + sz * 2, tmp.length);
        const L   = tmp.slice(lo, mid), R = tmp.slice(mid, hi);
        let i = 0, j = 0, k = lo;
        while (i < L.length && j < R.length) nxt[k++] = L[i] <= R[j] ? L[i++] : R[j++];
        while (i < L.length) nxt[k++] = L[i++];
        while (j < R.length) nxt[k++] = R[j++];
      }
      tmp = nxt.slice();
      steps.push({ arr: tmp.slice(), hi: -1, lo: -1, comps, swaps: 0 });
    }
    return { sorted, comps, swaps: 0, steps };
  }

  /**
   * QUICK SORT — O(n log n) avg, O(n²) worst (sorted input w/ last-element pivot)
   * Partitions around a pivot; elements ≤ pivot go left, > pivot go right.
   * Data structure: in-place array partitioning with two index pointers
   */
  function quickSort(arr) {
    const a = arr.slice(); let comps = 0, swaps = 0;
    const steps = [];
    function partition(lo, hi) {
      const pv = a[hi]; let i = lo - 1;
      for (let j = lo; j < hi; j++) {
        comps++;
        if (a[j] <= pv) { i++; [a[i], a[j]] = [a[j], a[i]]; swaps++; }
      }
      [a[i + 1], a[hi]] = [a[hi], a[i + 1]]; swaps++;
      steps.push({ arr: a.slice(), hi: i + 1, lo: hi, comps, swaps });
      return i + 1;
    }
    function qs(lo, hi) { if (lo < hi) { const p = partition(lo, hi); qs(lo, p-1); qs(p+1, hi); } }
    qs(0, a.length - 1);
    return { sorted: a, comps, swaps, steps };
  }

  /**
   * RANDOMIZED QUICK SORT — O(n log n) avg, O(n²) worst case extremely rare
   * Same as Quick Sort but pivot is chosen randomly, eliminating worst-case
   * on already-sorted input. Random pivot is swapped to end before partitioning.
   * Data structure: same as Quick Sort (in-place array)
   */
  function randomQuickSort(arr) {
    const a = arr.slice(); let comps = 0, swaps = 0;
    const steps = [];
    function partition(lo, hi) {
      const r = rand(lo, hi); [a[r], a[hi]] = [a[hi], a[r]]; swaps++; // random pivot
      const pv = a[hi]; let i = lo - 1;
      for (let j = lo; j < hi; j++) {
        comps++;
        if (a[j] <= pv) { i++; [a[i], a[j]] = [a[j], a[i]]; swaps++; }
      }
      [a[i + 1], a[hi]] = [a[hi], a[i + 1]]; swaps++;
      steps.push({ arr: a.slice(), hi: i + 1, lo: hi, comps, swaps });
      return i + 1;
    }
    function rqs(lo, hi) { if (lo < hi) { const p = partition(lo, hi); rqs(lo, p-1); rqs(p+1, hi); } }
    rqs(0, a.length - 1);
    return { sorted: a, comps, swaps, steps };
  }

  /**
   * COUNTING SORT — O(n + k) time and space, non-comparison sort
   * Counts occurrences of each value, then reconstructs the sorted array.
   * Data structure: count array (frequency table) of size k = max value
   */
  function countingSort(arr) {
    if (!arr.length) return { sorted: [], comps: 0, swaps: 0, steps: [] };
    const a = arr.slice(); const mx = Math.max(...a);
    const cnt = new Array(mx + 1).fill(0);
    let comps = 0;
    const steps = [];
    for (const v of a) { cnt[v]++; comps++; }
    const out = [];
    for (let i = 0; i <= mx; i++) {
      while (cnt[i]-- > 0) {
        out.push(i);
        steps.push({ arr: out.slice().concat(a.slice(out.length)), hi: out.length - 1, lo: -1, comps, swaps: 0 });
      }
    }
    return { sorted: out, comps, swaps: 0, steps };
  }

  /**
   * RADIX SORT (LSD, base-10) — O(nk) non-comparison sort
   * Sorts digit by digit from least to most significant using bucket sort each pass.
   * Data structure: 10 buckets (one per digit 0-9), rebuilt each pass
   */
  function radixSort(arr) {
    if (!arr.length) return { sorted: [], comps: 0, swaps: 0, steps: [] };
    let a = arr.slice(); let comps = 0; const steps = [];
    const mx = Math.max(...a);
    for (let exp = 1; Math.floor(mx / exp) > 0; exp *= 10) {
      const buckets = Array.from({ length: 10 }, () => []);
      for (const num of a) { buckets[Math.floor(num / exp) % 10].push(num); comps++; }
      a = buckets.flat();
      steps.push({ arr: a.slice(), hi: -1, lo: -1, comps, swaps: 0 });
    }
    return { sorted: a, comps, swaps: 0, steps };
  }

  /* ── ALGORITHM REGISTRY ──────────────────────────────────────────── */
  const ALGOS = {
    bubble:    { name: 'Bubble Sort',        emoji: '🫧', fn: bubbleSort,     complexity: 'O(n²)' },
    selection: { name: 'Selection Sort',     emoji: '🎯', fn: selectionSort,  complexity: 'O(n²)' },
    insertion: { name: 'Insertion Sort',     emoji: '📌', fn: insertionSort,  complexity: 'O(n²)' },
    merge:     { name: 'Merge Sort',         emoji: '🔀', fn: mergeSort,      complexity: 'O(n log n)' },
    quick:     { name: 'Quick Sort',         emoji: '⚡', fn: quickSort,      complexity: 'O(n log n)' },
    rquick:    { name: 'Random-Quick Sort',  emoji: '🎰', fn: randomQuickSort,complexity: 'O(n log n)' },
    counting:  { name: 'Counting Sort',      emoji: '🔢', fn: countingSort,   complexity: 'O(n+k)' },
    radix:     { name: 'Radix Sort',         emoji: '📻', fn: radixSort,      complexity: 'O(nk)' },
  };

  /* ── DATASET GENERATION ──────────────────────────────────────────── */
  let currentDataset = [];

  function makeDataset(size, type) {
    if (type === 'random')   return Array.from({ length: size }, () => rand(1, 999));
    if (type === 'sorted')   return Array.from({ length: size }, (_, i) => i + 1);
    if (type === 'reversed') return Array.from({ length: size }, (_, i) => size - i);
    return [];
  }

  function generateData() {
    const size  = parseInt(document.getElementById('sort-size').value);
    const dtype = document.getElementById('sort-dtype').value;
    if (dtype === 'custom') {
      const raw = document.getElementById('custom-nums').value;
      const parsed = raw.split(',').map(s => parseInt(s.trim())).filter(n => !isNaN(n) && n >= 0);
      if (!parsed.length) { alert('⚠️ Enter some numbers! e.g. 9, 3, 7, 1'); return; }
      currentDataset = parsed;
    } else {
      currentDataset = makeDataset(size, dtype);
    }
    resetVisualizer();
  }

  /* ── BENCHMARK ───────────────────────────────────────────────────── */
  async function runBenchmark() {
    if (!currentDataset.length) generateData();
    const selected = [...document.querySelectorAll('#algo-checks .check-label input:checked')].map(i => i.value);
    if (!selected.length) { alert('⚠️ Pick at least one algorithm!'); return; }

    const resultsCard = document.getElementById('sort-results-card');
    resultsCard.style.display = 'block';
    resultsCard.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
    document.getElementById('results-size').textContent = currentDataset.length;
    document.getElementById('results-tbody').innerHTML =
      '<tr><td colspan="6" style="text-align:center;padding:20px;color:#6B7280;font-weight:700">🏃 Running algorithms...</td></tr>';
    document.getElementById('bench-progress').style.width = '0%';

    const results = [];
    for (let i = 0; i < selected.length; i++) {
      const key  = selected[i];
      const algo = ALGOS[key];
      document.getElementById('bench-progress').style.width = `${((i + 1) / selected.length) * 100}%`;
      await sleep(5);
      const t0 = performance.now();
      const { sorted, comps, swaps } = algo.fn(currentDataset.slice());
      const time = performance.now() - t0;
      results.push({ key, name: algo.name, emoji: algo.emoji, time, comps, swaps, sorted, complexity: algo.complexity });
    }
    results.sort((a, b) => a.time - b.time);

    // sorted output preview (spec requirement)
    const s = results[0].sorted;
    document.getElementById('sorted-preview').textContent =
      `✅ Sorted Output (first 20): [${s.slice(0, 20).join(', ')}${s.length > 20 ? ', ...' : ''}]`;

    // build table — spec format: Dataset Size | Algorithm | Time (ms) | Comparisons | Swaps
    const maxTime = results[results.length - 1].time || 1;
    const tbody   = document.getElementById('results-tbody');
    tbody.innerHTML = '';
    results.forEach((r, idx) => {
      const pct = Math.max(4, Math.round((r.time / maxTime) * 100));
      const tr  = document.createElement('tr');
      if (idx === 0) tr.className = 'fastest';
      tr.innerHTML = `
        <td><strong>${idx + 1}</strong></td>
        <td>${r.emoji} <strong>${r.name}</strong> <span class="tag">${r.complexity}</span></td>
        <td><strong>${r.time.toFixed(2)}</strong></td>
        <td>${r.comps.toLocaleString()}</td>
        <td>${r.swaps.toLocaleString()}</td>
        <td><div class="time-bar-wrap"><div class="time-bar" style="width:${pct}%"></div></div></td>
      `;
      tbody.appendChild(tr);
    });

    confetti();
  }

  /* ── LIVE BAR VISUALIZER ─────────────────────────────────────────── */
  const canvas = document.getElementById('sort-canvas');
  const ctx    = canvas.getContext('2d');

  // Bar colors: normal, active (being swapped), pivot, done
  const BAR = { normal: '#C7D2FE', active: '#FF6B6B', pivot: '#FFE66D', done: '#4ADE80' };

  let visCurrent = [], visSteps = [], visIdx = 0, visRunning = false;

  function resizeCanvas() {
    canvas.width  = canvas.parentElement.clientWidth;
    canvas.height = canvas.parentElement.clientHeight;
  }
  window.addEventListener('resize', () => { resizeCanvas(); drawBars(visCurrent); });

  function drawBars(arr, hi = -1, lo = -1) {
    resizeCanvas();
    const W = canvas.width, H = canvas.height;
    ctx.clearRect(0, 0, W, H);
    if (!arr.length) return;
    const bw = W / arr.length;
    const mx = Math.max(...arr) || 1;
    for (let i = 0; i < arr.length; i++) {
      const bh    = (arr[i] / mx) * (H - 12);
      let   color = BAR.normal;
      if (i === hi) color = BAR.active;
      else if (i === lo) color = BAR.pivot;
      ctx.fillStyle = color;
      ctx.beginPath();
      ctx.roundRect(i * bw + 1, H - bh, bw - 2, bh, bw < 5 ? 0 : 3);
      ctx.fill();
    }
  }

  function resetVisualizer() {
    if (visRunning) { visRunning = false; }
    visIdx = 0; visSteps = [];
    const visSize = parseInt(document.getElementById('vis-size').value);
    const dtype   = document.getElementById('sort-dtype').value;
    visCurrent = dtype === 'custom'
      ? currentDataset.slice(0, visSize)
      : makeDataset(visSize, dtype === 'sorted' ? 'sorted' : dtype === 'reversed' ? 'reversed' : 'random');
    drawBars(visCurrent);
    document.getElementById('stat-comps').textContent = '0';
    document.getElementById('stat-swaps').textContent = '0';
    document.getElementById('stat-time').textContent  = '0';
    document.getElementById('stat-done').textContent  = '—';
    document.getElementById('sort-progress').style.width = '0%';
    document.getElementById('step-badge').textContent    = 'Ready!';
    document.getElementById('vis-play-btn').textContent  = '▶️ Play';
    document.getElementById('vis-algo-label').textContent = ALGOS[document.getElementById('vis-algo').value]?.name || '';
  }

  async function toggleVis() {
    const btn = document.getElementById('vis-play-btn');
    if (visRunning) { visRunning = false; btn.textContent = '▶️ Play'; return; }

    if (!visSteps.length) {
      const key = document.getElementById('vis-algo').value;
      const t0  = performance.now();
      const res = ALGOS[key].fn(visCurrent.slice());
      document.getElementById('stat-time').textContent = (performance.now() - t0).toFixed(2);
      visSteps = res.steps;
    }
    if (visIdx >= visSteps.length) visIdx = 0;

    visRunning = true;
    btn.textContent = '⏸️ Pause';

    const SPEED = { 1: 90, 2: 45, 3: 20, 4: 7, 5: 1 };
    while (visRunning && visIdx < visSteps.length) {
      const step = visSteps[visIdx];
      visCurrent  = step.arr;
      drawBars(step.arr, step.hi, step.lo);
      animCounter(document.getElementById('stat-comps'), step.comps);
      animCounter(document.getElementById('stat-swaps'), step.swaps);
      const pct = Math.round((visIdx / visSteps.length) * 100);
      document.getElementById('sort-progress').style.width = pct + '%';
      document.getElementById('step-badge').textContent = `Step ${visIdx + 1} / ${visSteps.length}`;
      visIdx++;
      await sleep(SPEED[parseInt(document.getElementById('vis-speed').value)] || 20);
    }

    if (visIdx >= visSteps.length) {
      visRunning = false;
      btn.textContent = '✅ Done!';
      drawBars(visCurrent);
      document.getElementById('stat-done').textContent = '✅';
      document.getElementById('sort-progress').style.width = '100%';
      document.getElementById('step-badge').textContent = `Done! ${visSteps.length} steps`;
      confetti();
    }
  }

  /* ── MODULE INIT ─────────────────────────────────────────────────── */
  function init() {
    generateData();
    setTimeout(resetVisualizer, 80);

    document.getElementById('sort-dtype').addEventListener('change', function () {
      document.getElementById('custom-input-wrap').style.display = this.value === 'custom' ? 'block' : 'none';
      generateData();
    });
    document.getElementById('vis-algo').addEventListener('change', resetVisualizer);
    document.getElementById('vis-size').addEventListener('change', resetVisualizer);
  }

  /* ── PUBLIC API ──────────────────────────────────────────────────── */
  return { init, generateData, runBenchmark, toggleVis, resetVisualizer };

})();
